name: GitHub Actions Demo

on:
  push:
    branches:
    - main
jobs:
  Job1:
    runs-on: unbuntu-latest
    steps:
      - run: |
          echo "Mal gucken was passiert..."

      - uses: actions/checkout@v4.1.0

      - name: List files in the repository
        run: |
          echo "The repository ${{ github.repository }} contains the following files:"
          tree
  
